repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev:  v3.4.0  # Use the sha / tag you want to point at
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements

  - repo: https://github.com/hhatto/autopep8.git
    rev: v2.1.0
    hooks:
      - id: autopep8
