# Generated by Django 5.0.3 on 2024-05-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iapp3_drf', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmType',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('film_type_name', models.CharField(max_length=2555, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=200)),
                ('duration', models.DecimalField(
                    decimal_places=2, default=0.0, max_digits=10)),
                ('release_date', models.DateField(auto_now=True)),
                ('film_type', models.ManyToManyField(to='iapp3_drf.filmtype')),
            ],
        ),
    ]
