# Generated by Django 5.0.3 on 2024-05-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iapp3_drf', '0003_filmtype_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('headquarters_location', models.CharField(max_length=100)),
                ('is_large_company', models.BooleanField(default=False)),
            ],
        ),
    ]
