# Generated by Django 5.0.3 on 2024-05-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_created=True)),
                ('post_name', models.CharField(
                    help_text='Enter which post upload', max_length=255)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
