# Generated by Django 5.0.3 on 2024-05-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iapp4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
