# Generated by Django 5.0.3 on 2024-05-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iapp4', '0002_alter_post_created_date_alter_post_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
