# Generated by Django 5.0.3 on 2024-05-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iapp4', '0003_post_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=1028, null=True)),
                ('content', models.CharField(
                    help_text='enter a good content', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
