# Generated by Django 5.0.1 on 2024-01-30 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i1app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shirt_size', models.CharField(choices=[
                 ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('instrument', models.CharField(
                    blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('num_star', models.IntegerField(default=0)),
                ('artist', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='i1app.musician')),
            ],
        ),
    ]
