# Generated by Django 5.0.3 on 2024-03-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i1app', '0002_customer_musician_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('launch_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
