# Generated by Django 5.0.3 on 2024-04-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('i1app', '0003_music'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
    ]
