# Generated by Django 5.0.3 on 2024-04-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i2app_signal', '0002_category_device_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
