name: Django CI/CD

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - first_new_branch
      - second_branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version:  3.11.5

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


